name = "MetaanalysisJulia"
uuid = "1b5533fc-62b5-4259-bafa-0d08af5bdd04"
authors = ["Arindam Basu"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
